stages:
    - test
    - examples
    - benchmarks
    - cppcheck


test_job:
    stage: test
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON ${BUILD_DIR}/..
    script:
        - make tests
        - cd ${BUILD_DIR}/tests && ./munkrestest
        - cd ${BUILD_DIR}
        - make coverage
        - gcovr --exclude 'tests' --exclude 'build' -r ..
    only:
        - devel


examples_job:
    stage: examples
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake ${BUILD_DIR}/..
    script:
        - make examples
    only:
        - devel


benchmarks_job:
    stage: benchmarks
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
    script:
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON -DMUNKRES_CPP_MATRIX_TYPE=Matrix -DMUNKRES_CPP_VALUE_TYPE=long\ double ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON -DMUNKRES_CPP_MATRIX_TYPE=matrix_armadillo -DMUNKRES_CPP_VALUE_TYPE=double ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON -DMUNKRES_CPP_MATRIX_TYPE=matrix_opencv -DMUNKRES_CPP_VALUE_TYPE=float ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON -DMUNKRES_CPP_MATRIX_TYPE=matrix_boost -DMUNKRES_CPP_VALUE_TYPE=long\ unsigned\ int ${BUILD_DIR}/..
        - make benchmarks
        - rm -rf CMake*
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON -DMUNKRES_CPP_MATRIX_TYPE=matrix_eigen -DMUNKRES_CPP_VALUE_TYPE=unsigned\ int ${BUILD_DIR}/..
        - make benchmarks
    only:
        - devel


cppcheck_job:
    stage: cppcheck
    image: registry.gitlab.com/gluttton/munkres-cpp
    before_script:
        - git checkout devel
        - BUILD_DIR=`pwd`/build
        - mkdir -p ${BUILD_DIR}
        - cd ${BUILD_DIR}
        - cmake -DCMAKE_BUILD_TYPE=Debug -DMUNKRESCPP_DEVEL_MODE=ON ${BUILD_DIR}/..
    script:
        - make cppcheck
        - cat cppcheck.report
    only:
        - devel

